import dotenv from 'dotenv';
import { CohereClient } from "cohere-ai";

dotenv.config();

// FUNCTION TO SEND THE REQUEST TO THE COHERE API
const sendPromptToCohere = async (author) => {
    const apiKey = process.env.API_KEY_COHERE;

    const prompt = `
    Autor: ${author}

    1. Reflexão do dia (curta) sobre o autor.
    2. Um desafio do dia relacionado ao autor.
    3. Uma história inspiradora sobre o autor.
    4. Uma curiosidade a respeito do autor.

    Observação: Me forneça somente os tópicos por paragrafos, sem numereção e sem títulos nenhum. Somente o texto de cada tópico mesmo.
    `;

    try {
        const cohere = new CohereClient({
            token: apiKey,
        });

        // SENDING THE MESSAGE TO THE API
        const response = await cohere.chat({
            message: prompt,
        });

        // EXTRACTING TEXT GENERATED BY THE API
        const text = response.text.trim();

        // SPLITTING TEXT INTO LINES AND CREATING AN OBJECT
        const lines = text.split('\n').map(line => line.trim()).filter(line => line); 

        const formattedResponse = {
            reflection: lines[0] || '',
            challenge: lines[1] || '',
            story: lines[2] || '',
            curiosity: lines[3] || '',
        };

        // RETURNS THE OBJECT WITH THE FORMATTED DATA
        return formattedResponse;

    } catch (error) {
        console.error('Error requesting Cohere API:', error.message);
        throw new Error('Error accessing Cohere API');
    }
};

export { sendPromptToCohere };